### ISSUE TITLE
Invoke-DetectPTH fails with Current Time issue

### ISSUE THREAD

**Issue by jbsullivan86** [cyberark/ketshash#1]
I receive the errors and the program will not run beyond this (Version 1.2):

"WARNING: Time differences (>= 3 second) found:"
WARNING: It will affect the results
WARNING: Please run as administrator'net time /set /y' on..."

I applied the suggested command as admin and the response showed "This command completed successfully"
When running the cmdlet again, I receive the same error msg

Thanks

Jbs

**Comment by g3rzi** [comment]
Hi Jbs,

What is the full (date, hours, minutes and seconds) current time on the target machine and on the DC (try to check it as parallel as you can)   ?

I put this warning when there is a difference more than 3 seconds between your target machine to your DC. 
It won't stop the detection but it might give a difference results (e.g. false negative - FN).
Another issue that can be is that the **checking of the time itself** is taking more time to get the time while the time difference is ok.

Some legitimate NTLM scenarios had events 4648 on the source machine 2-3 seconds before the NTLM event. 
Time differences can be more than that.  [Microsoft](https://technet.microsoft.com/en-us/library/jj852172(v=ws.11).aspx) set the default to 5 minutes on domain environment:

> It is advisable to set Maximum tolerance for computer clock synchronization to a value of 5 minutes.

I can solve it by increasing the time but this should be correlated with the check for event 4648. 
I just need to see that I am avoiding FN as much as I can. 
This can be tricky because if I will increase the time for, lets say 1 minute, it can check events 4648 that are not related to the NTLM event and cause FN.
I have couple of indicators that can help me to create correlation between the 4648 to the NTLM event.

I will do some changes and test them and update you.
Please update me also regarding the time differences between your target machine and DC.

Thanks

**Comment by g3rzi** [comment]
Hi jbsullivan86,

I uploaded an update (version 1.4), please try it.

I also thought about more flexible solutions for such scenarios:
- Checking the time difference between machines and searching for 4648 based on the time differences.
- Solving the time of the checking itself by measuring how much time it took with `Measure-Command`.
- A generic solution: adjusting the time of one of the machines to match the other machine's time. Example: ComputerA: 10:00 AM, ComputerB: 11:00 AM. Checking the difference (+1) and refer ComputerA's time as 11:00 AM instead of 10:00. This solution need to be check with caution because it requires to check all the exceptions and bugs that might have. This is why one of the requirements is that the machines will be synchronized but I know that this is not always happens in production environment.

**Comment by jbsullivan86** [comment]
Thank you,
Much appreciated getting your follow-up.
I will try again when back at work this week!

Best,

James

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by g3rzi** [comment]
I am closing it for now.
If you still have this error, I will re-open it.
